apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.env.AWS_SECRET_ACCESS_KEY }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.env.AWS_ACCESS_KEY_ID }}
            - name: AWS_REGION
              value: {{ .Values.env.AWS_REGION }}
            - name: S3_BUCKET
              value: {{ .Values.env.S3_BUCKET }}
          ports:
            - name: smtp
              containerPort: 25
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /bin/bash
              - /app/healthcheck.sh
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - /app/healthcheck.sh
            initialDelaySeconds: 30
            periodSeconds: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
